"""обновление user

Revision ID: 7d509b8a08fc
Revises: 6b63cb9f09f6
Create Date: 2020-04-23 00:53:00.847358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d509b8a08fc'
down_revision = '6b63cb9f09f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles', table_name='user')
    op.create_index(op.f('ix_user_roles'), 'user', ['roles'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles'), table_name='user')
    op.create_index('ix_user_roles', 'user', ['roles'], unique=1)
    # ### end Alembic commands ###
