"""Full Profile model

Revision ID: cd0b043bdde4
Revises: 11083a358acb
Create Date: 2020-05-02 02:27:18.902189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b043bdde4'
down_revision = '11083a358acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('fullname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_profile_fullname'), 'profile', ['fullname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_fullname'), table_name='profile')
    op.drop_column('profile', 'fullname')
    # ### end Alembic commands ###
