"""+profile

Revision ID: e53f3aa8b1c3
Revises: 7d509b8a08fc
Create Date: 2020-05-01 17:35:36.857079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53f3aa8b1c3'
down_revision = '7d509b8a08fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    # ### end Alembic commands ###
